// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MusicStoreClient.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class SampleEntity
    {
        /// <summary>
        /// Initializes a new instance of the SampleEntity class.
        /// </summary>
        public SampleEntity() { }

        /// <summary>
        /// Initializes a new instance of the SampleEntity class.
        /// </summary>
        public SampleEntity(string title = default(string), string artist = default(string), DateTime? createdDate = default(DateTime?), string mp3Blob = default(string), string sampleMp3Blob = default(string), string sampleMp3Url = default(string), DateTime? sampleDate = default(DateTime?), string partitionKey = default(string), string rowKey = default(string), DateTime? timestamp = default(DateTime?), string eTag = default(string))
        {
            Title = title;
            Artist = artist;
            CreatedDate = createdDate;
            Mp3Blob = mp3Blob;
            SampleMp3Blob = sampleMp3Blob;
            SampleMp3Url = sampleMp3Url;
            SampleDate = sampleDate;
            PartitionKey = partitionKey;
            RowKey = rowKey;
            Timestamp = timestamp;
            ETag = eTag;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Title")]
        public string Title { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Artist")]
        public string Artist { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CreatedDate")]
        public DateTime? CreatedDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Mp3Blob")]
        public string Mp3Blob { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SampleMp3Blob")]
        public string SampleMp3Blob { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SampleMp3Url")]
        public string SampleMp3Url { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SampleDate")]
        public DateTime? SampleDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PartitionKey")]
        public string PartitionKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RowKey")]
        public string RowKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Timestamp")]
        public DateTime? Timestamp { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ETag")]
        public string ETag { get; set; }

    }
}
