// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MusicStoreClient.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Sample
    {
        /// <summary>
        /// Initializes a new instance of the Sample class.
        /// </summary>
        public Sample() { }

        /// <summary>
        /// Initializes a new instance of the Sample class.
        /// </summary>
        public Sample(string sampleID = default(string), string title = default(string), string artist = default(string), string sampleMp3Url = default(string))
        {
            SampleID = sampleID;
            Title = title;
            Artist = artist;
            SampleMp3Url = sampleMp3Url;
        }

        /// <summary>
        /// Sample ID
        /// </summary>
        [JsonProperty(PropertyName = "SampleID")]
        public string SampleID { get; set; }

        /// <summary>
        /// Title of the sample
        /// </summary>
        [JsonProperty(PropertyName = "Title")]
        public string Title { get; set; }

        /// <summary>
        /// Artist Name
        /// </summary>
        [JsonProperty(PropertyName = "Artist")]
        public string Artist { get; set; }

        /// <summary>
        /// the blob sample url
        /// </summary>
        [JsonProperty(PropertyName = "SampleMp3Url")]
        public string SampleMp3Url { get; set; }

    }
}
